### ISSUE TITLE
Make all sub-pages visible in tree

### ISSUE THREAD

**Issue by DominicDirkx** [tudat-team/tudat-space#44]
With the reorganization of the user guide, various pages are no longer shown in the TOC tree on the left of the page, and can only be found by the right path of clicking through pages, making the site more difficult to use. I would propose modifying the TOC tree, so that _all_ existing pages are visible there. Adding an extra level in the TOC may then be useful.

**Comment by FilippoOggionni** [comment]
This was solved by using the regular toctree in sphinx, with the addition of the following options:
- :hidden: (so that the toctree is not actually shown in the page it is placed in)
- :titlesonly: (so that page sections do not show up in the toctree)

It might be that some pages are not shown, but I will take care of the missing ones!
