### ISSUE TITLE
Go through outdated content

### ISSUE THREAD

**Issue by FilippoOggionni** [tudat-team/tudat-space#52]
This concerns the following files, located [here](https://github.com/tudat-team/tudat-space/tree/master/docs/source/outdated):

- [x] `EstimatableParameterSet_Appendix.rst` (not sure where it comes from)
- [x] `developer_guide_tudat.rst` (this can be moved to the tudat-developer docs, together with the `_src_developer` directory)
- [x] `example_application_10.rst` (outdated example, shall we delete it or adapt it?)

**Comment by DominicDirkx** [comment]
The first one used to be on the dynamics simulator page (?) It has since been incorporated into other pages. The example application #10 has been rewritten and can be deleted. Indeed, the developer guide page should be merged with existing developer docs. @FilippoOggionni, could you link this to the relevant open issue on developer docs (?) if any?

**Comment by FilippoOggionni** [comment]
Thanks for the info!
I deleted the first and third files, while I moved the second one in the directory with developer content (see 0fa2708fb4bdf158c690043f60389ec86b651170). 
I will link that directory to #55.
