### ISSUE TITLE
Review Tudat Estimation pages

### ISSUE THREAD

**Issue by DominicDirkx** [tudat-team/tudat-space#99]
The pages here:
https://docs.tudat.space/en/latest/_src_user_guide/state_estimation.html
need to be reviewed, and input provided on:
- Whether the functionality is clearly explained, and where additional clarifications are needed
- Whether the associated pages in the API documentation (https://py.api.tudat.space/en/latest/estimation_setup.html and https://py.api.tudat.space/en/latest/estimation.html are clear), and where additional clarification is needed
- Where the interfaces could/should be improved
- Which additional functionality should be added/exposed
- Which example applications should be added to clarify the documentation

**Comment by kgzenk** [comment]
Extensive comments per section to be found in the files attached to this post - something might/will be redundant with some of the following general comments:

- personally, I am a huge fan of justified text (provided it is a well justified text, not Word-style), don't know how that would work with many code and API references in the text
- the estimation API page is just one massive chunk what could be a bit scary at first glance, maybe adapt a structure similar to the sections in the documentation
- use one overall example file (only LRO, MEX, or ...) instead of "spacecraft-hopping" per section which happens especially in the first sections
- clearly explain what the following code-snippet is going to do BEFORE the snippet, not afterwards; it happens several times that one has no clue what the snippet/function presented there actually does until reading what comes just after the code-block
- the first sentence(s) of the section just grows longer and longer and longer with every new section (after having defined ... and having done ... and ...) just remove, it should follow naturally from the order of the sections and the links at the end of the individual sections
- first discuss and explain the easy ways of setting up a pair of link ends in the 'Link Ends Setup' section (what is now shortly done right at the end, but further expand on that) before going into detail how to manually do so
- more wrapper classes; example would be to directly enable bias in observation_setup.one_way_range() by putting bias = 0.0 as standard and not having to define the bias manually as observation_setup.absolute_bias( 0.01 ), makes the code easier to read and understand OR another example light_time_correction_settings = light_time_correction_settings could become light_time_correction_settings = ['Sun', order = 1] something in that direction
- make a separate section with 'Theory' that is necessary to know how tudat internally works, but not necessary to use it (aka help lazy students or users by filtering what is crucial to know and what is nice to know, but not important to make tudat work), such as for instance the theory about Doppler types
- personally, I am not sure if the 'Observation Models' subsection 'Available model types' is more to be put in the API with less text and more a let the code explain itself attitude, if not I found the current list-layout not very clear (read: very confusing, since it is to much text and bold and etc.)
- give more examples on the 'Observation Simulation' page, that's what I want to know as (potential) user of tudat; how can I adapt the observations to my needs, what can I get out of the tool, and how complex is it to get what I want, I suppose the other sections are (more or less) standardized for other tools as well
- combine the two sections 'Estimation Settings' and 'Performing the Estimation' and re-structure in a way that theory and associated code blocks are better connected/linked with each other
- Further expand on this new (or the two old, if not combined) 'Estimation' chapter(s), maybe even more code snippets; however I fear that there is not much left code-wise to show
- introduce some sort of comprehensive 'cheat sheet' with a compact step-by-step introduction what to do in which order to perform a successful estimation (as a sort of quick catching-up and brain re-activation after some weeks/months of tudat-iary absence)


[1 - Link Ends Setup.pdf](https://github.com/tudat-team/tudat-space/files/10559878/1.-.Link.Ends.Setup.pdf)
[2 - Observation. Model Setup.pdf](https://github.com/tudat-team/tudat-space/files/10559879/2.-.Observation.Model.Setup.pdf)
[2-1 - Observation Models.pdf](https://github.com/tudat-team/tudat-space/files/10559880/2-1.-.Observation.Models.pdf)
[3 - Observation Simulaiton.pdf](https://github.com/tudat-team/tudat-space/files/10559882/3.-.Observation.Simulaiton.pdf)
[4 - Estimation Settings.pdf](https://github.com/tudat-team/tudat-space/files/10559883/4.-.Estimation.Settings.pdf)
[5 - Performing the Estimation.pdf](https://github.com/tudat-team/tudat-space/files/10559884/5.-.Performing.the.Estimation.pdf)

**Comment by irmakcavdar** [comment]
Hello guys! Here also I have a small feedback document that I made. I still have some parts of the API to be reviewed and thinking of some examples so an additional feedback on that will follow for sure. 
[Estimation_Page_Feedback.pdf](https://github.com/tudat-team/tudat-space/files/10566546/Estimation_Page_Feedback.pdf)

**Comment by DominicDirkx** [comment]
> 
>     personally, I am a huge fan of justified text (provided it is a well justified text, not Word-style), don't know how that would work with many code and API references in the text
>     the estimation API page is just one massive chunk what could be a bit scary at first glance, maybe adapt a structure similar to the sections in the documentation
>     use one overall example file (only LRO, MEX, or ...) instead of "spacecraft-hopping" per section which happens especially in the first sections
>     clearly explain what the following code-snippet is going to do BEFORE the snippet, not afterwards; it happens several times that one has no clue what the snippet/function presented there actually does until reading what comes just after the code-block
>     the first sentence(s) of the section just grows longer and longer and longer with every new section (after having defined ... and having done ... and ...) just remove, it should follow naturally from the order of the sections and the links at the end of the individual sections
>     first discuss and explain the easy ways of setting up a pair of link ends in the 'Link Ends Setup' section (what is now shortly done right at the end, but further expand on that) before going into detail how to manually do so
>     more wrapper classes; example would be to directly enable bias in observation_setup.one_way_range() by putting bias = 0.0 as standard and not having to define the bias manually as observation_setup.absolute_bias( 0.01 ), makes the code easier to read and understand OR another example light_time_correction_settings = light_time_correction_settings could become light_time_correction_settings = ['Sun', order = 1] something in that direction
>     make a separate section with 'Theory' that is necessary to know how tudat internally works, but not necessary to use it (aka help lazy students or users by filtering what is crucial to know and what is nice to know, but not important to make tudat work), such as for instance the theory about Doppler types
>     personally, I am not sure if the 'Observation Models' subsection 'Available model types' is more to be put in the API with less text and more a let the code explain itself attitude, if not I found the current list-layout not very clear (read: very confusing, since it is to much text and bold and etc.)
>     give more examples on the 'Observation Simulation' page, that's what I want to know as (potential) user of tudat; how can I adapt the observations to my needs, what can I get out of the tool, and how complex is it to get what I want, I suppose the other sections are (more or less) standardized for other tools as well
>     combine the two sections 'Estimation Settings' and 'Performing the Estimation' and re-structure in a way that theory and associated code blocks are better connected/linked with each other
>     Further expand on this new (or the two old, if not combined) 'Estimation' chapter(s), maybe even more code snippets; however I fear that there is not much left code-wise to show
>     introduce some sort of comprehensive 'cheat sheet' with a compact step-by-step introduction what to do in which order to perform a successful estimation (as a sort of quick catching-up and brain re-activation after some weeks/months of tudat-iary absence)
>

**Comment by DominicDirkx** [comment]
@irmakcavdar, thanks for the many suggestions as well :) Below is my (quick) reply to the points in your document:

Main page:

1.) Good idea. Also, this can be highlighted more in the first few (basic) estimation examples

2.) Sounds good

3.) That would be nice, we have some diagrams for the overall propagation as well. Those can be added here as well :)

4. Agreed!

Variational equations:

1.) One of many spelling errors, I suspect

2.) This is a tricky one... The variational equations (and state transition/sensitivity matrix) are useful for various things apart from estimation (uncertainty analysis, mission design...), so I'd prefer to not keep them under estimation, as people may misinterpret the potential scope. But, I also agree that the current place may be confusing. Any 'intermediate' suggestions would be most welcome!

Estimation settings:

1.) This is a good point, and is (partially) a remnant of the older Tudat structure. The covariance is indeed part of the estimation, but is not a proper estimator by itself. What it is often used for is to *simulate* an estimation. The covariance, as calculated here, does an uncertainty propagation from observation errors to parameter errors (and under several assumptions provides the multivariate probability distribution from which a real estimation is but a single realization). Let's discuss how best to approach this point

2.) Work in progress :) 
   b) The main scope of the estimation module would be post-mission science analysis, where the batch method would (usually, in planetary missions) be the way to go. But I agree that the methodology is not applicable to all cases. This should be made clear (and updated when we have more!)
c) Agreed

3) To be discussed :)

Notes: Link ends setup
------------------------------
Will do later

**Comment by irmakcavdar** [comment]
Hello everyone, I gave a quick look at the comments and the feedbacks from Dominic, indeed I can start with changes (from tomorrow onwards). I do have one small question: I believe I will do the edits on GitHub, is that correct? Already when I am on the website I can see "Edit on GitHub" written on top right.

**Comment by DominicDirkx** [comment]
Hi Irmak, the 'Edit on Github' is typically used for very minor changes. What you'll be doing doesn't fall in that category, I think :) This page gives instructions on how to locally build the tudat-space website:
https://tudat-developer.readthedocs.io/en/latest/primer/docs/sphinx.html#sphinx-documentation
make sure to put the tudat-space repository on the develop branch (which corresponds to the 'latest' version).

Today, someone else got this error:
```

Extension error:
Could not import extension sphinxcontrib.contentui (exception: No module named 'sphinxcontrib.contentui')
```

when first building. Use the following command in the terminal (after activating the tudat-docs environment) to fix it:

`pip install sphinxcontrib-contentui`

Once you're done with your changes (or part of them, that you'd like someone to review), put them on a different branch, and push them to the tudat-space repo. To merge your changes into the tudat-space develop branch, you can make a pull request.

If any of the above steps are unclear, feel free to post on Slack for some help. I realize it's a lot of new stuff :)
